---
title: "git_00"
author: " Shael Quintero"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Girt with a boyish garb for boyish task,  
Eager she wields her spade: yet loves as well.  
Rest on the friendly knee, intent to ask.  
The tale one loves to tell.   




## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Whose woods these are I think I know.   
His house is in the village though;   
He will not see me stopping here   
To watch his woods fill up with snow




## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,   
Shining with all his might.    
He did his very best to make.     
The billows smooth and bright.  

And this was odd, because it was.  
The middle of the night.   
The moon was shining sulkily,    
Because she thought the sun.   
Had got no business to be there.   
After the day was done —    
It's very rude of him," she said,    
To come and spoil the fun."    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
And then I heard them lift a Box   
And creak across my Soul    
With those same Boots of Lead, again,    
Then Space – began to toll,     
As all the Heavens were a Bell,    
And Being, but an Ear,     
And I, and Silence, some strange Race,    
Wrecked, solitary, here 





git config --global user.name “squintero3 “
git config --global user.email “squintero3@students.avc.edu”
git config --global http.sslverify "false" 
git config --global core.autocrlf true
git config --global credential.helper 'cache --timeout 3600



